<?php
	require_once("fnConfig.php");
	require_once("fnClass.php");
	require_once("fnConnDB.php");
	require_once("fnAccount.php");
	require_once("fnChar.php");
	require_once("fnGuild.php");
	require_once("fnArenaTeam.php");
	require_once("fnTicket.php");
	require_once("fnRaSocket.php");
	require_once("fnCreatures.php");
?>